### PR TITLE
Add getConnectionMask() method

### PR DESCRIPTION
**Pull request by Renegade334**
ref: #5 

Calling `getConnectionMask()` when one or more of the components haven't been set yet, has been left as undefined behaviour. (In reality, `sprintf` just casts `null` to the empty string.) Don't think this needs to be addressed or mentioned - should be pretty obvious.

I have bumped the minimum PHP version to 5.4.2, for continuity, and added PHP 7 to the build grid.

### CODE REVIEW

**Comment by elazar** [comment]
This looks good, though in the interest of concision, being that this method is part of a connection object, should we consider shortening the method name to `getMask()`?

**Comment by Renegade334** [comment]
Sure. Also, the interface issue - if we add to the interface, then extended classes will herp a derp.

**Comment by elazar** [comment]
"The interface issue" being also adding this method to `ConnectionInterface`? The only bad thing I see about that is that any code relying on this method would have to use `Connection` instead, which would require that any custom connection implementations extend `Connection` in order to be usable with said code. Alternatively, we could call this a BC break and bump to v2.

**Comment by Renegade334** [comment]
Yup, that one. I only raise it since you mentioned it previously. If other classes like Client rely on the method, it should definitely be interfaced.

**Pull request merged**
